<style>
.straas-banner-live{
	width:100%;
}
</style>
<?php
//echo "conf: ".Mage::getConfig()->getNode('default/straas/token/content')."<br/>";
function getLive($straas_live_id = null, $token = null){
	$url =  Mage::getConfig()->getNode('default/straas/urls/base') . Mage::getConfig()->getNode('default/straas/urls/create_live') . '/' . $straas_live_id;
	if($token == null) $token = Mage::getConfig()->getNode('default/straas/token/content');
	
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json', 'Authorization: Bearer '.$token));
	//curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer '.$token));
	//curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

	$result = curl_exec($ch);
	
	curl_close($ch);
    
    $result = json_decode($result);
	
	
	return $result;
}

function renderLive($stream){
	$html = '';
	//$html .= '<video width="352" height="198" controls><source src="'.$stream->stream_url.'" type="application/x-mpegURL"></video>';
	//$html .= '<iframe frameborder="0" allowfullscreen="allowfullscreen" width="960" height="420" src="'.$stream->embed_url.'"></iframe>';
	$html .= '<iframe class="straas-banner-live" frameborder="0" allowfullscreen="allowfullscreen" height="590" src="'.$stream->embed_url.'"></iframe>';
	return $html;
}





// get all the resources related to the live video
$token = Mage::getConfig()->getNode('default/straas/token/content');

$model  = Mage::getModel('live/straaslive');
$liveid = $this->getData('liveid');
if($live = $model->load($liveid)){
	//echo "id".$live->getData('res_live_id');
	//echo "<pre>"; print_r($live); echo "</pre>";
	// request live stream
	$stream = getLive($live->getData('res_live_id'));
	//echo "<pre>"; print_r($stream); echo "</pre>";
	echo renderLive($stream);
}
else{
	//echo "null";
}








//show the video
//print_r( $model->getTitle());

//print_r($model);
?>
